language: ruby
cache: bundler

rvm:
  - 2.2
  - jruby

jdk:
  - openjdk7

matrix:
  exclude:
    - rvm: 2.2
      jdk: openjdk7

services:
  - redis-server
  - elasticsearch

before_install:
  - gem update --system
  - gem --version

before_script:
  - source /etc/lsb-release && echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install rethinkdb -y

notifications:
  email:
    recipients:
      - jeff.carley@gmail.com
    on_failure: change
    on_success: never
