db:
  image: rethinkdb:2.1.3
  ports:
    - "8080:8080"
redis:
  image: redis:3.0.3
  ports:
    - "6379:6379"
search:
  image: elasticsearch:1.7.2
  volumes:
    - '/home/vagrant/apps/inventory/docker/elasticsearch/config:/usr/share/elasticsearch/config'
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment:
    PORT: 9292
    RAILS_ENV: 'development'
  ports:
    - '9292:9292'
  links:
    - db:RETHINKDB_HOST
    - redis
    - search
  volumes:
    - '/home/vagrant/apps/inventory:/app/user'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 9292
    RAILS_ENV: 'development'
  ports:
    - '9292:9292'
  links:
    - db:RETHINKDB_HOST
    - redis
    - search
  volumes:
    - '/home/vagrant/apps/inventory:/app/user'
