db:
  image: rethinkdb:2.1.3
  ports:
    - "8080:8080"
redis:
  image: redis:3.0.3
  ports:
    - "6379:6379"
search:
  image: elasticsearch:1.7.2
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment:
    PORT: 3000
  ports:
    - '3000:3000'
  links:
    - db
    - redis
    - search
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 3000
  ports:
    - '3000:3000'
  links:
    - db
    - redis
    - search
  volumes:
    - '.:/app/user'
