db:
  image: rethinkdb:2.1.3
  ports:
    - "8080:8080"
redis:
  image: redis:3.0.3
  ports:
    - "6379:6379"
search:
  build: ./docker/elasticsearch/
  ports:
    - "9200:9200"
  volumes:
    - '/home/vagrant/apps/inventory/docker/elasticsearch/config:/usr/share/elasticsearch/config'
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment:
    PORT: 9292
    RAILS_ENV: 'development'
  ports:
    - '9292:9292'
  links:
    - db:RETHINKDB_HOST
    - redis
    - search
  volumes:
    - '/home/vagrant/apps/inventory:/app/user'
  labels:
    com.finishfirstsoftware.description: "inventory"
sidekiq:
  build: .
  command: 'bash -c ''bundle exec sidekiq -C config/sidekiq.yml -P tmp/pids/sidekiq.pid'''
  working_dir: /app/user
  environment:
    RAILS_ENV: 'development'
  links:
    - db:RETHINKDB_HOST
    - redis
    - search
  volumes:
    - '/home/vagrant/apps/inventory:/app/user'
  labels:
    com.finishfirstsoftware.description: "inventory"
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 9292
    RAILS_ENV: 'development'
    JRUBY_OPTS: --dev
    JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
  ports:
    - '9292:9292'
  links:
    - db:RETHINKDB_HOST
    - redis
    - search
  volumes:
    - '/home/vagrant/apps/inventory:/app/user'
  labels:
    com.finishfirstsoftware.description: "inventory"
